/* ==========================================================================
   BILL DATA — Central data store for all tracked bills
   Update this file when bills progress. All pages pull from here.
   ========================================================================== */

// Update this constant whenever bill data changes
const LAST_UPDATED = { date: "04/07/26", time: "06:03 PM EDT" };

const BILLS = [
  /* ===== ANTI-LGBTQ+ BILLS ===== */
  {
    id: "hb249",
    bill: "HB 249",
    title: "Indecent Exposure Modernization Act",
    nickname: "Drag Ban",
    officialTitle: "Enact the Indecent Exposure Modernization Act",
    stance: "anti",
    status: "passed-house",
    statusLabel: "Passed House → In Senate",
    statusColor: "#dc2626",
    categories: ["expression", "anti-trans"],
    categoryLabels: ["Expression", "Anti-Trans"],
    description:
      "Creates 'unlawful adult cabaret performance' with a definition reaching gender expression differing from 'biological sex.' Penalties escalate from misdemeanors to felonies when minors are present.",
    sponsors: "Rep. Angela N. King (R-84), Rep. Josh Williams (R-44)",
    lastAction: "In Senate — awaiting committee assignment (as of April 4, 2026)",
    nextDate: "Awaiting Senate committee assignment",
    houseVote: "Passed 63–32 on March 25, 2026",
    chamber: "house",
    currentStep: 5,
    pipelineDates: {
      0: "Apr 29, 2025",
      1: "May 7, 2025",
      3: "Mar 25, 2026",
      4: "Mar 25, 2026",
      5: "Mar 26, 2026",
    },
    url: "/issues/hb249",
    legislatureUrl: "https://www.legislature.ohio.gov/legislation/136/hb249",
    textUrl:
      "https://search-prod.lis.state.oh.us/api/v2/general_assembly_136/legislation/hb249/00_IN/pdf/",
  },
  {
    id: "hb693",
    bill: "HB 693",
    title: "Affirming Families First Act",
    nickname: "Parental Rejection Shield",
    officialTitle: "Enact the Affirming Families First Act",
    stance: "anti",
    status: "in-committee",
    statusLabel: "In Committee",
    statusColor: "#f59e0b",
    categories: ["youth", "anti-trans"],
    categoryLabels: ["Youth / Family", "Anti-Trans"],
    description:
      "Shields parents who reject a child's trans identity from abuse/neglect charges. Redefines 'affirmation' as acknowledging sex at birth only. Includes right to seek conversion-style therapy.",
    sponsors: "Rep. Gary Click (R-88), Rep. Josh Williams (R-44)",
    lastAction: "2nd hearing (proponent testimony) in House Judiciary — March 25, 2026",
    nextDate: "Opponent testimony expected next",
    chamber: "house",
    currentStep: 2,
    pipelineDates: { 0: "Feb 10, 2026", 1: "Feb 18, 2026", 2: "Mar 25, 2026" },
    url: "/issues/hb693",
    legislatureUrl: "https://www.legislature.ohio.gov/legislation/136/hb693",
    textUrl:
      "https://search-prod.lis.state.oh.us/api/v2/general_assembly_136/legislation/hb693/00_IN/pdf/",
  },
  {
    id: "hb798",
    bill: "HB 798",
    title: "Privacy Protection Act",
    nickname: "Omnibus Anti-Trans Bill",
    officialTitle: "Enact the Privacy Protection Act",
    stance: "anti",
    status: "introduced",
    statusLabel: "Introduced",
    statusColor: "#3b82f6",
    categories: ["anti-trans", "education", "corrections"],
    categoryLabels: ["Anti-Trans", "Education", "Corrections"],
    description:
      "Unusually broad: sex-segregated facilities, school name/pronoun mandates, government document restrictions, and private right of action for facility violations.",
    sponsors: "Rep. Josh Williams (R-44)",
    lastAction: "Introduced — March 31, 2026",
    nextDate: "Awaiting committee assignment",
    chamber: "house",
    currentStep: 0,
    pipelineDates: { 0: "Mar 31, 2026" },
    url: "/issues/hb798",
    legislatureUrl: "https://www.legislature.ohio.gov/legislation/136/hb798",
    textUrl:
      "https://search-prod.lis.state.oh.us/api/v2/general_assembly_136/legislation/hb798/00_IN/pdf/",
  },
  {
    id: "hb796",
    bill: "HB 796",
    title: "Inmate Housing by Biological Sex",
    nickname: "Prison Trans Housing Ban",
    officialTitle:
      "Ensure inmates, prisoners housed according to biological sex",
    stance: "anti",
    status: "introduced",
    statusLabel: "Introduced",
    statusColor: "#3b82f6",
    categories: ["corrections", "anti-trans"],
    categoryLabels: ["Corrections", "Anti-Trans"],
    description:
      "Requires incarcerated people be housed 'in accordance with their biological sex,' overriding individualized safety assessments for transgender inmates.",
    sponsors: "Rep. Josh Williams (R-44)",
    lastAction: "Introduced — March 25, 2026",
    nextDate: "Awaiting committee assignment",
    chamber: "house",
    currentStep: 0,
    pipelineDates: { 0: "Mar 25, 2026" },
    url: "/issues/hb796",
    legislatureUrl: "https://www.legislature.ohio.gov/legislation/136/hb796",
    textUrl:
      "https://search-prod.lis.state.oh.us/api/v2/general_assembly_136/legislation/hb796/00_IN/pdf/",
  },
  {
    id: "hb190",
    bill: "HB 190",
    title: "Given Name Act",
    nickname: "Forced Outing / Pronoun Ban",
    officialTitle: "Enact the Given Name Act",
    stance: "anti",
    status: "in-committee",
    statusLabel: "In Committee",
    statusColor: "#f59e0b",
    categories: ["education", "anti-trans"],
    categoryLabels: ["Education", "Anti-Trans"],
    description:
      "Restricts names and pronouns in schools. Requires staff to report student gender-identity accommodation requests to parents. Penalties include 10% withholding of state foundation aid.",
    sponsors: "Rep. Johnathan Newman (R-80), Rep. Josh Williams (R-44)",
    lastAction: "1st hearing in House Education — April 29, 2025",
    nextDate: "Additional hearings expected",
    chamber: "house",
    currentStep: 2,
    pipelineDates: { 0: "Mar 24, 2025", 1: "Mar 26, 2025", 2: "Apr 29, 2025" },
    url: "/issues/hb190",
    legislatureUrl: "https://www.legislature.ohio.gov/legislation/136/hb190",
    textUrl:
      "https://search-prod.lis.state.oh.us/api/v2/general_assembly_136/legislation/hb190/00_IN/pdf/",
  },
  {
    id: "hb155",
    bill: "HB 155",
    title: "Prohibit DEI in Public Schools",
    nickname: "K–12 DEI Ban",
    officialTitle:
      "Prohibit diversity, equity, and inclusion in public schools",
    stance: "anti",
    status: "in-committee",
    statusLabel: "In Committee",
    statusColor: "#f59e0b",
    categories: ["education"],
    categoryLabels: ["Education / DEI"],
    description:
      "Prohibits DEI programs in schools. Explicitly reaches contracting around sexual orientation, gender identity, and gender expression — banning LGBTQIA+-inclusive programming.",
    sponsors: "Rep. Beth Lear (R-61), Rep. Josh Williams (R-44)",
    lastAction: "2nd hearing in House Education — May 20, 2025",
    nextDate: "Additional hearings expected",
    chamber: "house",
    currentStep: 2,
    pipelineDates: { 0: "Mar 6, 2025", 1: "Mar 19, 2025", 2: "May 20, 2025" },
    url: "/issues/hb155",
    legislatureUrl: "https://www.legislature.ohio.gov/legislation/136/hb155",
    textUrl:
      "https://search-prod.lis.state.oh.us/api/v2/general_assembly_136/legislation/hb155/00_IN/pdf/",
  },
  {
    id: "sb113",
    bill: "SB 113",
    title: "Prohibit DEI in Public Schools (Senate)",
    nickname: "Senate DEI Ban",
    officialTitle:
      "Prohibit diversity, equity, and inclusion in public schools",
    stance: "anti",
    status: "in-committee",
    statusLabel: "In Committee",
    statusColor: "#f59e0b",
    categories: ["education"],
    categoryLabels: ["Education / DEI"],
    description:
      "Senate companion to HB 155. Requires school boards to prohibit DEI structures, trainings, offices, and contracting. Suppresses LGBTQIA+-inclusive initiatives.",
    sponsors: "Sen. Andrew Brenner (R-19)",
    lastAction: "2nd hearing in Senate Education — March 25, 2026",
    nextDate: "Additional hearings expected",
    chamber: "senate",
    currentStep: 2,
    pipelineDates: { 2: "Mar 25, 2026" },
    url: "/issues/sb113",
    legislatureUrl: "https://www.legislature.ohio.gov/legislation/136/sb113",
    textUrl:
      "https://search-prod.lis.state.oh.us/api/v2/general_assembly_136/legislation/sb113/00_IN/pdf/",
  },
  {
    id: "hb172",
    bill: "HB 172",
    title: "Minor Mental Health Consent",
    nickname: "Youth Therapy Consent Rollback",
    officialTitle:
      "Prohibit mental health service to minors without parental consent",
    stance: "anti",
    status: "in-committee",
    statusLabel: "In Committee",
    statusColor: "#f59e0b",
    categories: ["youth"],
    categoryLabels: ["Youth / Family"],
    description:
      "Removes ability of minors (14+) to access limited outpatient mental health services without parental consent. Threatens LGBTQ youth who need confidential care.",
    sponsors: "Rep. Johnathan Newman (R-80)",
    lastAction: "Opponent testimony in House Health — November 19, 2025",
    nextDate: "Additional hearings or committee vote",
    chamber: "house",
    currentStep: 2,
    pipelineDates: { 0: "Mar 12, 2025", 1: "Mar 19, 2025", 2: "Nov 19, 2025" },
    url: "/issues/hb172",
    legislatureUrl: "https://www.legislature.ohio.gov/legislation/136/hb172",
    textUrl:
      "https://search-prod.lis.state.oh.us/api/v2/general_assembly_136/legislation/hb172/00_IN/pdf/",
  },
  {
    id: "hb196",
    bill: "HB 196",
    title: "Candidate Name Disclosure",
    nickname: "Deadnaming Candidates Bill",
    officialTitle:
      "Regards candidate nomination protests, names on candidacy forms",
    stance: "anti",
    status: "in-committee",
    statusLabel: "In Committee",
    statusColor: "#f59e0b",
    categories: ["elections"],
    categoryLabels: ["Elections / Privacy"],
    description:
      "Expands candidate 'former legal names' disclosure and protest mechanisms. Disproportionately impacts trans candidates, effectively mandating public deadnaming.",
    sponsors: "Rep. Rodney Creech (R-40), Rep. Angela N. King (R-84)",
    lastAction: "1st hearing in House General Government — April 29, 2025",
    nextDate: "Additional hearings expected",
    chamber: "house",
    currentStep: 2,
    pipelineDates: { 0: "Mar 24, 2025", 1: "Mar 26, 2025", 2: "Apr 29, 2025" },
    url: "/issues/hb196",
    legislatureUrl: "https://www.legislature.ohio.gov/legislation/136/hb196",
    textUrl:
      "https://search-prod.lis.state.oh.us/api/v2/general_assembly_136/legislation/hb196/00_IN/pdf/",
  },
  {
    id: "hb262",
    bill: "HB 262",
    title: "Designate Natural Family Month",
    nickname: "Anti-LGBTQ Family Framing",
    officialTitle: "Designate Natural Family Month",
    stance: "anti",
    status: "in-committee",
    statusLabel: "In Committee",
    statusColor: "#f59e0b",
    categories: ["youth"],
    categoryLabels: ["Youth / Family"],
    description:
      "Establishes 'Natural Family Month' promoting a heteronormative 'one biological born man, woman' family structure — excluding same-sex parents and nontraditional families.",
    sponsors: "Rep. Beth Lear (R-61), Rep. Josh Williams (R-44)",
    lastAction: "Proponent testimony — September 30, 2025",
    nextDate: "Additional hearings or committee vote",
    chamber: "house",
    currentStep: 2,
    pipelineDates: { 0: "May 13, 2025", 1: "May 14, 2025", 2: "Sep 30, 2025" },
    url: "/issues/hb262",
    legislatureUrl: "https://www.legislature.ohio.gov/legislation/136/hb262",
    textUrl:
      "https://search-prod.lis.state.oh.us/api/v2/general_assembly_136/legislation/hb262/00_IN/pdf/",
  },

  /* ===== PRO-LGBTQ+ BILLS ===== */
  {
    id: "sb70",
    bill: "SB 70",
    title: "Ohio Fairness Act",
    nickname: "Statewide Nondiscrimination Protections",
    officialTitle: "Enact the Ohio Fairness Act regarding nondiscrimination protections",
    stance: "pro",
    status: "in-committee",
    statusLabel: "In Committee",
    statusColor: "#22c55e",
    categories: ["civil-rights"],
    categoryLabels: ["Civil Rights"],
    description:
      "Adds sexual orientation and gender identity to Ohio's existing nondiscrimination statutes, covering employment, housing, and public accommodations statewide.",
    sponsors: "Sen. Nickie Antonio (D-23)",
    lastAction: "Referred to Senate Judiciary Committee",
    nextDate: "Awaiting committee hearing",
    chamber: "senate",
    currentStep: 1,
    pipelineDates: { 0: "Feb 11, 2025", 1: "Feb 19, 2025" },
    url: "/issues/sb70",
    legislatureUrl: "https://www.legislature.ohio.gov/legislation/136/sb70",
    textUrl:
      "https://search-prod.lis.state.oh.us/api/v2/general_assembly_136/legislation/sb70/00_IN/pdf/",
  },
  {
    id: "hb136",
    bill: "HB 136",
    title: "Ohio Fairness Act (House)",
    nickname: "House Nondiscrimination Companion",
    officialTitle: "Enact the Ohio Fairness Act regarding nondiscrimination protections",
    stance: "pro",
    status: "in-committee",
    statusLabel: "In Committee",
    statusColor: "#22c55e",
    categories: ["civil-rights"],
    categoryLabels: ["Civil Rights"],
    description:
      "House companion to SB 70. Extends Ohio's civil rights protections to include sexual orientation and gender identity across employment, housing, and public accommodations.",
    sponsors: "Rep. Bride Rose Sweeney (D-16), Rep. Brett Hillyer (R-37)",
    lastAction: "Referred to House Civil Justice Committee",
    nextDate: "Awaiting committee hearing",
    chamber: "house",
    currentStep: 1,
    pipelineDates: { 0: "Feb 25, 2025", 1: "Mar 5, 2025" },
    url: "/issues/hb136",
    legislatureUrl: "https://www.legislature.ohio.gov/legislation/136/hb136",
    textUrl:
      "https://search-prod.lis.state.oh.us/api/v2/general_assembly_136/legislation/hb136/00_IN/pdf/",
  },
  {
    id: "sb71",
    bill: "SB 71",
    title: "Conversion Therapy Ban",
    nickname: "Protect LGBTQ+ Youth from Conversion Therapy",
    officialTitle: "Prohibit licensed professionals from practicing conversion therapy on minors",
    stance: "pro",
    status: "in-committee",
    statusLabel: "In Committee",
    statusColor: "#22c55e",
    categories: ["healthcare", "youth"],
    categoryLabels: ["Healthcare", "Youth / Family"],
    description:
      "Prohibits state-licensed mental health professionals from subjecting minors to conversion therapy — a discredited practice rejected by every major medical association.",
    sponsors: "Sen. Nickie Antonio (D-23)",
    lastAction: "Referred to Senate Health Committee",
    nextDate: "Awaiting committee hearing",
    chamber: "senate",
    currentStep: 1,
    pipelineDates: { 0: "Feb 11, 2025", 1: "Feb 19, 2025" },
    url: "/issues/sb71",
    legislatureUrl: "https://www.legislature.ohio.gov/legislation/136/sb71",
    textUrl:
      "https://search-prod.lis.state.oh.us/api/v2/general_assembly_136/legislation/sb71/00_IN/pdf/",
  },
  {
    id: "hb300",
    bill: "HB 300",
    title: "Conversion Therapy Ban (House)",
    nickname: "House Conversion Therapy Companion",
    officialTitle: "Prohibit licensed professionals from practicing conversion therapy on minors",
    stance: "pro",
    status: "introduced",
    statusLabel: "Introduced",
    statusColor: "#22c55e",
    categories: ["healthcare", "youth"],
    categoryLabels: ["Healthcare", "Youth / Family"],
    description:
      "House companion to SB 71. Bans conversion therapy on minors by licensed professionals. Supported by the American Medical Association, American Psychological Association, and American Academy of Pediatrics.",
    sponsors: "Rep. Bride Rose Sweeney (D-16)",
    lastAction: "Introduced — May 20, 2025",
    nextDate: "Awaiting committee assignment",
    chamber: "house",
    currentStep: 0,
    pipelineDates: { 0: "May 20, 2025" },
    url: "/issues/hb300",
    legislatureUrl: "https://www.legislature.ohio.gov/legislation/136/hb300",
    textUrl:
      "https://search-prod.lis.state.oh.us/api/v2/general_assembly_136/legislation/hb300/00_IN/pdf/",
  },
  {
    id: "sb211",
    bill: "SB 211",
    title: "Love Makes a Family Week",
    nickname: "Celebrate Diverse Ohio Families",
    officialTitle: "Designate Love Makes a Family Week in Ohio",
    stance: "pro",
    status: "introduced",
    statusLabel: "Introduced",
    statusColor: "#22c55e",
    categories: ["youth"],
    categoryLabels: ["Youth / Family"],
    description:
      "Designates a week celebrating the diversity of Ohio families — including LGBTQ+ families, adoptive families, and nontraditional households. A direct counterpoint to HB 262's 'Natural Family Month.'",
    sponsors: "Sen. Nickie Antonio (D-23)",
    lastAction: "Introduced — October 14, 2025",
    nextDate: "Awaiting committee assignment",
    chamber: "senate",
    currentStep: 0,
    pipelineDates: { 0: "Oct 14, 2025" },
    url: "/issues/sb211",
    legislatureUrl: "https://www.legislature.ohio.gov/legislation/136/sb211",
    textUrl:
      "https://search-prod.lis.state.oh.us/api/v2/general_assembly_136/legislation/sb211/00_IN/pdf/",
  },
  {
    id: "hb327",
    bill: "HB 327",
    title: "PRIDE Act",
    nickname: "Parental Rights for Affirming Families",
    officialTitle: "Enact the Parental Rights in Diverse Environments Act",
    stance: "pro",
    status: "in-committee",
    statusLabel: "In Committee",
    statusColor: "#22c55e",
    categories: ["youth", "civil-rights"],
    categoryLabels: ["Youth / Family", "Civil Rights"],
    description:
      "Protects parents who affirm and support their LGBTQ+ children from state interference. Ensures affirming parenting decisions cannot be used as grounds for custody challenges or abuse allegations.",
    sponsors: "Rep. Dontavius Jarrells (D-25), Rep. Ismail Mohamed (D-3)",
    lastAction: "Referred to House Families, Aging, and Human Services Committee",
    nextDate: "Awaiting committee hearing",
    chamber: "house",
    currentStep: 1,
    pipelineDates: { 0: "Jun 3, 2025", 1: "Jun 11, 2025" },
    url: "/issues/hb327",
    legislatureUrl: "https://www.legislature.ohio.gov/legislation/136/hb327",
    textUrl:
      "https://search-prod.lis.state.oh.us/api/v2/general_assembly_136/legislation/hb327/00_IN/pdf/",
  },

  /* ===== MIXED BILLS ===== */
  {
    id: "hb306",
    bill: "HB 306",
    title: "Hate Crimes Act",
    nickname: "Hate Crimes — Excludes Trans Protections",
    officialTitle: "Enact the Ohio Hate Crimes Act",
    stance: "mixed",
    status: "in-committee",
    statusLabel: "In Committee",
    statusColor: "#eab308",
    categories: ["civil-rights"],
    categoryLabels: ["Civil Rights"],
    description:
      "Creates enhanced penalties for hate crimes based on race, religion, national origin, disability, and sexual orientation — but notably excludes gender identity, leaving transgender Ohioans without protection.",
    sponsors: "Rep. Brett Hillyer (R-37), Rep. Bride Rose Sweeney (D-16)",
    lastAction: "Referred to House Criminal Justice Committee",
    nextDate: "Awaiting committee hearing",
    chamber: "house",
    currentStep: 1,
    pipelineDates: { 0: "May 27, 2025", 1: "Jun 4, 2025" },
    url: "/issues/hb306",
    legislatureUrl: "https://www.legislature.ohio.gov/legislation/136/hb306",
    textUrl:
      "https://search-prod.lis.state.oh.us/api/v2/general_assembly_136/legislation/hb306/00_IN/pdf/",
  },
];

// Helper to find a bill by ID
function getBillById(id) {
  return BILLS.find((b) => b.id === id);
}
