/* ==========================================================================
   BILL DATA, Central data store for all tracked bills
   Update this file when bills progress. All pages pull from here.

   Source of truth: Supabase `public.bills` + `public.bill_categories`
   Last sync from migrations 20260423000000 / 20260423000001 / 20260424000002.

   Bill order follows the editorial priority rubric:
     1. Active anti-equality bills with most recent floor activity
     2. Active anti-equality bills in committee by priority
     3. Already-signed / overridden anti-equality law (scorecard context)
     4. Active pro-equality bills
     5. Mixed / nuanced bills
   ========================================================================== */

// Update this constant whenever bill data changes
const LAST_UPDATED = { date: "04/22/26", time: "06:00 PM EDT" };

const BILLS = [
  /* ============================================================
     ANTI-LGBTQ+ BILLS, ACTIVE, ON THE FLOOR OR MOVING
     ============================================================ */
  {
    id: "hb249",
    bill: "HB 249",
    title: "Indecent Exposure Modernization Act",
    nickname: "Drag Ban",
    officialTitle: "Enact the Indecent Exposure Modernization Act",
    stance: "anti",
    status: "passed-house",
    statusLabel: "Passed House → In Senate",
    statusColor: "#dc2626",
    categories: ["expression", "anti-trans"],
    categoryLabels: ["Expression", "Anti-Trans"],
    description:
      "Creates 'unlawful adult cabaret performance' with a definition reaching gender expression differing from 'biological sex.' Penalties escalate from misdemeanors to felonies when minors are present.",
    sponsors: "Rep. Angela N. King (R-84), Rep. Josh Williams (R-44)",
    lastAction: "Referred to Senate committee, April 15, 2026",
    nextDate: "Awaiting Senate committee hearing",
    houseVote: "Passed 63-32 on March 25, 2026",
    chamber: "house",
    currentStep: 6,
    pipelineDates: {
      0: "Apr 29, 2025",
      1: "May 7, 2025",
      3: "Mar 25, 2026",
      4: "Mar 25, 2026",
      5: "Mar 26, 2026",
      6: "Apr 15, 2026",
    },
    generalAssembly: "136th",
    effectiveDate: null,
    enactedTextUrl: null,
    equalityImpactNote:
      "Criminalizes gender expression deviating from 'biological sex' in any venue where a minor could be present. Drag performers, trans and nonbinary Ohioans, and any event with inclusive casting face misdemeanor to felony exposure.",
    impactedCommunities: ["drag-artists", "transgender-adults", "nonbinary", "queer-youth"],
    url: "/issues/hb249",
    legislatureUrl: "https://www.legislature.ohio.gov/legislation/136/hb249",
    textUrl:
      "https://search-prod.lis.state.oh.us/api/v2/general_assembly_136/legislation/hb249/00_IN/pdf/",
  },
  {
    id: "sb34",
    bill: "SB 34",
    title: "Display of Founding Documents of Historic Significance Act",
    nickname: "Ten Commandments Classroom Displays",
    officialTitle:
      "Enact the Display of Founding Documents of Historic Significance Act",
    stance: "anti",
    status: "passed-senate",
    statusLabel: "Passed Senate → In House",
    statusColor: "#dc2626",
    categories: ["education-dei"],
    categoryLabels: ["Education / DEI"],
    description:
      "Requires school boards to adopt policies displaying at least four of nine 'founding documents', including the Ten Commandments, in social studies and history classrooms. Permits private donors (e.g., the Center for Christian Virtue) to fund displays, inviting religious-right messaging into public schools. Passed the Ohio Senate 23-10 on November 20, 2025.",
    sponsors: "Sen. Terry Johnson (R-14)",
    lastAction: "Referred to House Education Committee, February 4, 2026",
    nextDate: "Awaiting House committee hearing",
    senateVote: "Passed 23-10 on November 20, 2025",
    chamber: "senate",
    currentStep: 6,
    pipelineDates: {
      0: "Feb 2025",
      3: "Apr 8, 2025",
      4: "Nov 20, 2025",
      5: "Nov 20, 2025",
      6: "Feb 4, 2026",
    },
    generalAssembly: "136th",
    effectiveDate: null,
    enactedTextUrl: null,
    equalityImpactNote:
      "Invites Christian nationalist messaging into Ohio public schools. Privately funded Ten Commandments displays normalize religious-right framing in classrooms serving LGBTQ+ students.",
    impactedCommunities: ["lgbtq-students", "religious-minority-students", "all-lgbtq"],
    url: "/issues/sb34",
    legislatureUrl: "https://www.legislature.ohio.gov/legislation/136/sb34",
    textUrl:
      "https://search-prod.lis.state.oh.us/api/v2/general_assembly_136/legislation/sb34/00_IN/pdf/",
  },

  /* ============================================================
     ANTI-LGBTQ+ BILLS, ACTIVE, IN COMMITTEE OR INTRODUCED
     ============================================================ */
  {
    id: "hb798",
    bill: "HB 798",
    title: "Privacy Protection Act",
    nickname: "Omnibus Anti-Trans Bill",
    officialTitle: "Enact the Privacy Protection Act",
    stance: "anti",
    status: "introduced",
    statusLabel: "Introduced",
    statusColor: "#3b82f6",
    categories: ["anti-trans", "education-dei", "corrections"],
    categoryLabels: ["Anti-Trans", "Education / DEI", "Corrections"],
    description:
      "Unusually broad: sex-segregated facilities, school name/pronoun mandates, government document restrictions, and private right of action for facility violations.",
    sponsors: "Rep. Josh Williams (R-44)",
    lastAction: "Introduced, March 31, 2026",
    nextDate: "Awaiting committee assignment",
    chamber: "house",
    currentStep: 0,
    pipelineDates: { 0: "Mar 31, 2026" },
    generalAssembly: "136th",
    effectiveDate: null,
    enactedTextUrl: null,
    equalityImpactNote:
      "Omnibus anti-trans bill layering bathroom, pronoun, document, and prison housing restrictions into a single vehicle. Grants private right of action, inviting targeted lawsuits against trans Ohioans.",
    impactedCommunities: ["transgender-youth", "transgender-adults", "nonbinary", "lgbtq-students", "incarcerated-trans"],
    url: "/issues/hb798",
    legislatureUrl: "https://www.legislature.ohio.gov/legislation/136/hb798",
    textUrl:
      "https://search-prod.lis.state.oh.us/api/v2/general_assembly_136/legislation/hb798/00_IN/pdf/",
  },
  {
    id: "hb796",
    bill: "HB 796",
    title: "Inmate Housing by Biological Sex",
    nickname: "Prison Trans Housing Ban",
    officialTitle:
      "Ensure inmates, prisoners housed according to biological sex",
    stance: "anti",
    status: "introduced",
    statusLabel: "Introduced",
    statusColor: "#3b82f6",
    categories: ["corrections", "anti-trans"],
    categoryLabels: ["Corrections", "Anti-Trans"],
    description:
      "Requires incarcerated people be housed 'in accordance with their biological sex,' overriding individualized safety assessments for transgender inmates.",
    sponsors: "Rep. Josh Williams (R-44)",
    lastAction: "Introduced, March 25, 2026",
    nextDate: "Awaiting committee assignment",
    chamber: "house",
    currentStep: 0,
    pipelineDates: { 0: "Mar 25, 2026" },
    generalAssembly: "136th",
    effectiveDate: null,
    enactedTextUrl: null,
    equalityImpactNote:
      "Forces transgender inmates into housing by 'biological sex' regardless of individualized safety assessment. Puts trans women at known elevated risk of assault in men's facilities.",
    impactedCommunities: ["incarcerated-trans", "transgender-adults"],
    url: "/issues/hb796",
    legislatureUrl: "https://www.legislature.ohio.gov/legislation/136/hb796",
    textUrl:
      "https://search-prod.lis.state.oh.us/api/v2/general_assembly_136/legislation/hb796/00_IN/pdf/",
  },
  {
    id: "hb693",
    bill: "HB 693",
    title: "Affirming Families First Act",
    nickname: "Parental Rejection Shield",
    officialTitle: "Enact the Affirming Families First Act",
    stance: "anti",
    status: "in-committee",
    statusLabel: "In Committee",
    statusColor: "#f59e0b",
    categories: ["youth-family", "anti-trans"],
    categoryLabels: ["Youth / Family", "Anti-Trans"],
    description:
      "Shields parents who reject a child's trans identity from abuse/neglect charges. Redefines 'affirmation' as acknowledging sex at birth only. Includes right to seek conversion-style therapy.",
    sponsors: "Rep. Gary Click (R-88), Rep. Josh Williams (R-44)",
    lastAction: "2nd hearing (proponent testimony) in House Judiciary, March 25, 2026",
    nextDate: "Opponent testimony expected next",
    chamber: "house",
    currentStep: 2,
    pipelineDates: { 0: "Feb 10, 2026", 1: "Feb 18, 2026", 2: "Mar 25, 2026" },
    generalAssembly: "136th",
    effectiveDate: null,
    enactedTextUrl: null,
    equalityImpactNote:
      "Shields parents who reject an LGBTQ+ child from abuse or neglect findings and preserves a route to conversion practices. Inverts child-welfare protections for the most vulnerable youth.",
    impactedCommunities: ["transgender-youth", "queer-youth", "lgbtq-families"],
    url: "/issues/hb693",
    legislatureUrl: "https://www.legislature.ohio.gov/legislation/136/hb693",
    textUrl:
      "https://search-prod.lis.state.oh.us/api/v2/general_assembly_136/legislation/hb693/00_IN/pdf/",
  },
  {
    id: "hb602",
    bill: "HB 602",
    title: "State Flag Display Restriction",
    nickname: "Pride Flag Ban on State Property",
    officialTitle:
      "Limit types of flags that state agencies may display on grounds or buildings",
    stance: "anti",
    status: "in-committee",
    statusLabel: "In Committee",
    statusColor: "#f59e0b",
    categories: ["expression"],
    categoryLabels: ["Expression"],
    description:
      "Limits flags on state-owned property to the U.S., Ohio, POW/MIA, and pre-approved agency flags, effectively banning Pride flags from state buildings and grounds. Revives language that Gov. DeWine line-item-vetoed from the FY26-27 budget (HB 96).",
    sponsors: "Rep. D.J. Swearingen (R-89), Rep. Rodney Creech (R-40)",
    lastAction:
      "Sponsor testimony in House General Government, week of March 30, 2026",
    nextDate: "Additional hearings expected",
    chamber: "house",
    currentStep: 2,
    pipelineDates: { 0: "Nov 18, 2025", 2: "Mar 30, 2026" },
    generalAssembly: "136th",
    effectiveDate: null,
    enactedTextUrl: null,
    equalityImpactNote:
      "Bans Pride flags from state-owned property by limiting permissible flag types. Erases visible LGBTQ+ recognition at state agencies and public universities.",
    impactedCommunities: ["all-lgbtq", "lgbtq-state-workers", "lgbtq-students"],
    url: "/issues/hb602",
    legislatureUrl: "https://www.legislature.ohio.gov/legislation/136/hb602",
    textUrl:
      "https://search-prod.lis.state.oh.us/api/v2/general_assembly_136/legislation/hb602/00_IN/pdf/",
  },
  {
    id: "hb457",
    bill: "HB 457",
    title: "Politically-Motivated Crimes",
    nickname: "Sexual Orientation Aggravator Removal",
    officialTitle: "Create enhanced penalties for politically motivated offenses",
    stance: "anti",
    status: "in-committee",
    statusLabel: "In Committee",
    statusColor: "#f59e0b",
    categories: ["civil-rights", "anti-trans"],
    categoryLabels: ["Civil Rights", "Anti-Trans"],
    description:
      "Creates new aggravated-murder offenses for politically motivated violence and mandatory prison terms. Adds 'biological sex' as an aggravating factor while removing 'sexual orientation' from Ohio's existing aggravating-factor list, a net loss for LGBTQ+ protections.",
    sponsors: "Rep. Jack K. Daniels (R-32), Rep. Josh Williams (R-44)",
    lastAction: "Referred to House Criminal Justice Committee",
    nextDate: "Awaiting committee hearing",
    chamber: "house",
    currentStep: 1,
    pipelineDates: {},
    generalAssembly: "136th",
    effectiveDate: null,
    enactedTextUrl: null,
    equalityImpactNote:
      "Net loss for LGBTQ+ criminal-law protections: adds 'biological sex' as an aggravating factor while stripping 'sexual orientation' from Ohio's existing list. Trans and bisexual Ohioans lose standing under Ohio's aggravator regime.",
    impactedCommunities: ["transgender-adults", "gay-lesbian-adults", "bisexual-adults", "all-lgbtq"],
    url: "/issues/hb457",
    legislatureUrl: "https://www.legislature.ohio.gov/legislation/136/hb457",
    textUrl:
      "https://search-prod.lis.state.oh.us/api/v2/general_assembly_136/legislation/hb457/00_IN/pdf/",
  },
  {
    id: "hb190",
    bill: "HB 190",
    title: "Given Name Act",
    nickname: "Forced Outing / Pronoun Ban",
    officialTitle: "Enact the Given Name Act",
    stance: "anti",
    status: "in-committee",
    statusLabel: "In Committee",
    statusColor: "#f59e0b",
    categories: ["education-dei", "anti-trans"],
    categoryLabels: ["Education / DEI", "Anti-Trans"],
    description:
      "Restricts names and pronouns in schools. Requires staff to report student gender-identity accommodation requests to parents. Penalties include 10% withholding of state foundation aid.",
    sponsors: "Rep. Johnathan Newman (R-80), Rep. Josh Williams (R-44)",
    lastAction: "1st hearing in House Education, April 29, 2025",
    nextDate: "Additional hearings expected",
    chamber: "house",
    currentStep: 2,
    pipelineDates: { 0: "Mar 24, 2025", 1: "Mar 26, 2025", 2: "Apr 29, 2025" },
    generalAssembly: "136th",
    effectiveDate: null,
    enactedTextUrl: null,
    equalityImpactNote:
      "Forces school staff to out students to parents and bans use of chosen names or pronouns. Penalty structure puts districts at financial risk for affirming trans and nonbinary students.",
    impactedCommunities: ["transgender-youth", "nonbinary-youth", "queer-youth", "lgbtq-students"],
    url: "/issues/hb190",
    legislatureUrl: "https://www.legislature.ohio.gov/legislation/136/hb190",
    textUrl:
      "https://search-prod.lis.state.oh.us/api/v2/general_assembly_136/legislation/hb190/00_IN/pdf/",
  },
  {
    id: "hb155",
    bill: "HB 155",
    title: "Prohibit DEI in Public Schools",
    nickname: "K-12 DEI Ban",
    officialTitle:
      "Prohibit diversity, equity, and inclusion in public schools",
    stance: "anti",
    status: "in-committee",
    statusLabel: "In Committee",
    statusColor: "#f59e0b",
    categories: ["education-dei"],
    categoryLabels: ["Education / DEI"],
    description:
      "Prohibits DEI programs in schools. Explicitly reaches contracting around sexual orientation, gender identity, and gender expression, banning LGBTQIA+-inclusive programming.",
    sponsors: "Rep. Beth Lear (R-61), Rep. Josh Williams (R-44)",
    lastAction: "2nd hearing in House Education, May 20, 2025",
    nextDate: "Additional hearings expected",
    chamber: "house",
    currentStep: 2,
    pipelineDates: { 0: "Mar 6, 2025", 1: "Mar 19, 2025", 2: "May 20, 2025" },
    generalAssembly: "136th",
    effectiveDate: null,
    enactedTextUrl: null,
    equalityImpactNote:
      "Prohibits K-12 DEI programs with language explicitly reaching sexual orientation, gender identity, and gender expression. Shuts down inclusive curriculum and supports for LGBTQ+ students.",
    impactedCommunities: ["lgbtq-students", "queer-youth", "transgender-youth"],
    url: "/issues/hb155",
    legislatureUrl: "https://www.legislature.ohio.gov/legislation/136/hb155",
    textUrl:
      "https://search-prod.lis.state.oh.us/api/v2/general_assembly_136/legislation/hb155/00_IN/pdf/",
  },
  {
    id: "sb113",
    bill: "SB 113",
    title: "Prohibit DEI in Public Schools (Senate)",
    nickname: "Senate DEI Ban",
    officialTitle:
      "Prohibit diversity, equity, and inclusion in public schools",
    stance: "anti",
    status: "in-committee",
    statusLabel: "In Committee",
    statusColor: "#f59e0b",
    categories: ["education-dei"],
    categoryLabels: ["Education / DEI"],
    description:
      "Senate companion to HB 155. Requires school boards to prohibit DEI structures, trainings, offices, and contracting. Suppresses LGBTQIA+-inclusive initiatives.",
    sponsors: "Sen. Andrew Brenner (R-19)",
    lastAction: "2nd hearing in Senate Education, March 25, 2026",
    nextDate: "Additional hearings expected",
    chamber: "senate",
    currentStep: 2,
    pipelineDates: { 2: "Mar 25, 2026" },
    generalAssembly: "136th",
    effectiveDate: null,
    enactedTextUrl: null,
    equalityImpactNote:
      "Senate companion to HB 155. Requires school boards to eliminate DEI structures, trainings, and contracts. Silences LGBTQ+ inclusive programming at the district level.",
    impactedCommunities: ["lgbtq-students", "queer-youth", "transgender-youth"],
    url: "/issues/sb113",
    legislatureUrl: "https://www.legislature.ohio.gov/legislation/136/sb113",
    textUrl:
      "https://search-prod.lis.state.oh.us/api/v2/general_assembly_136/legislation/sb113/00_IN/pdf/",
  },
  {
    id: "hb172",
    bill: "HB 172",
    title: "Minor Mental Health Consent",
    nickname: "Youth Therapy Consent Rollback",
    officialTitle:
      "Prohibit mental health service to minors without parental consent",
    stance: "anti",
    status: "in-committee",
    statusLabel: "In Committee",
    statusColor: "#f59e0b",
    categories: ["youth-family"],
    categoryLabels: ["Youth / Family"],
    description:
      "Removes ability of minors (14+) to access limited outpatient mental health services without parental consent. Threatens LGBTQ youth who need confidential care.",
    sponsors: "Rep. Johnathan Newman (R-80)",
    lastAction: "Opponent testimony in House Health, November 19, 2025",
    nextDate: "Additional hearings or committee vote",
    chamber: "house",
    currentStep: 2,
    pipelineDates: { 0: "Mar 12, 2025", 1: "Mar 19, 2025", 2: "Nov 19, 2025" },
    generalAssembly: "136th",
    effectiveDate: null,
    enactedTextUrl: null,
    equalityImpactNote:
      "Repeals the 1989-era pathway that let minors 14+ access up to six confidential outpatient mental-health sessions. Cuts off a critical lifeline for LGBTQ+ youth in hostile households.",
    impactedCommunities: ["queer-youth", "transgender-youth", "lgbtq-students"],
    url: "/issues/hb172",
    legislatureUrl: "https://www.legislature.ohio.gov/legislation/136/hb172",
    textUrl:
      "https://search-prod.lis.state.oh.us/api/v2/general_assembly_136/legislation/hb172/00_IN/pdf/",
  },
  {
    id: "sb274",
    bill: "SB 274",
    title: "Minor Mental Health Consent (Senate)",
    nickname: "Senate Companion to HB 172",
    officialTitle:
      "Prohibit mental health service to minors without parental consent",
    stance: "anti",
    status: "in-committee",
    statusLabel: "In Committee",
    statusColor: "#f59e0b",
    categories: ["youth-family"],
    categoryLabels: ["Youth / Family"],
    description:
      "Senate companion to HB 172. Repeals ORC 5122.04, eliminating the 1989-era provision that allows minors 14+ to access up to six outpatient mental-health sessions without parental consent. Closes a critical confidential-care pathway for LGBTQ+ youth.",
    sponsors: "Sen. Jerry Cirino (R-18), Sen. Andrew Brenner (R-19)",
    lastAction: "Referred to Senate Health Committee, October 1, 2025",
    nextDate: "Awaiting committee hearing",
    chamber: "senate",
    currentStep: 1,
    pipelineDates: { 0: "Sep 30, 2025", 1: "Oct 1, 2025" },
    generalAssembly: "136th",
    effectiveDate: null,
    enactedTextUrl: null,
    equalityImpactNote:
      "Senate companion to HB 172. Repeals ORC 5122.04, eliminating confidential outpatient mental-health access for minors. LGBTQ+ youth lose a key safety valve when parents are the source of harm.",
    impactedCommunities: ["queer-youth", "transgender-youth", "lgbtq-students"],
    url: "/issues/sb274",
    legislatureUrl: "https://www.legislature.ohio.gov/legislation/136/sb274",
    textUrl:
      "https://search-prod.lis.state.oh.us/api/v2/general_assembly_136/legislation/sb274/00_IN/pdf/",
  },
  {
    id: "hb196",
    bill: "HB 196",
    title: "Candidate Name Disclosure",
    nickname: "Deadnaming Candidates Bill",
    officialTitle:
      "Regards candidate nomination protests, names on candidacy forms",
    stance: "anti",
    status: "in-committee",
    statusLabel: "In Committee",
    statusColor: "#f59e0b",
    categories: ["elections-privacy"],
    categoryLabels: ["Elections / Privacy"],
    description:
      "Expands candidate 'former legal names' disclosure and protest mechanisms. Disproportionately impacts trans candidates, effectively mandating public deadnaming.",
    sponsors: "Rep. Rodney Creech (R-40), Rep. Angela N. King (R-84)",
    lastAction: "1st hearing in House General Government, April 29, 2025",
    nextDate: "Additional hearings expected",
    chamber: "house",
    currentStep: 2,
    pipelineDates: { 0: "Mar 24, 2025", 1: "Mar 26, 2025", 2: "Apr 29, 2025" },
    generalAssembly: "136th",
    effectiveDate: null,
    enactedTextUrl: null,
    equalityImpactNote:
      "Expands ballot-access protest mechanisms around 'former legal names'. Operates as forced public deadnaming of transgender candidates and a deterrent to trans and nonbinary Ohioans running for office.",
    impactedCommunities: ["transgender-adults", "nonbinary", "trans-candidates"],
    url: "/issues/hb196",
    legislatureUrl: "https://www.legislature.ohio.gov/legislation/136/hb196",
    textUrl:
      "https://search-prod.lis.state.oh.us/api/v2/general_assembly_136/legislation/hb196/00_IN/pdf/",
  },
  {
    id: "hb262",
    bill: "HB 262",
    title: "Designate Natural Family Month",
    nickname: "Anti-LGBTQ Family Framing",
    officialTitle: "Designate Natural Family Month",
    stance: "anti",
    status: "in-committee",
    statusLabel: "In Committee",
    statusColor: "#f59e0b",
    categories: ["youth-family"],
    categoryLabels: ["Youth / Family"],
    description:
      "Establishes 'Natural Family Month' promoting a heteronormative 'one biological born man, woman' family structure, excluding same-sex parents and nontraditional families.",
    sponsors: "Rep. Beth Lear (R-61), Rep. Josh Williams (R-44)",
    lastAction: "Proponent testimony, September 30, 2025",
    nextDate: "Additional hearings or committee vote",
    chamber: "house",
    currentStep: 2,
    pipelineDates: { 0: "May 13, 2025", 1: "May 14, 2025", 2: "Sep 30, 2025" },
    generalAssembly: "136th",
    effectiveDate: null,
    enactedTextUrl: null,
    equalityImpactNote:
      "Codifies a 'one biological born man, woman' family definition in an Ohio observance. Rhetorical foundation for excluding same-sex parents, adoptive families, and chosen family from state recognition.",
    impactedCommunities: ["same-sex-couples", "lgbtq-families", "adoptive-families"],
    url: "/issues/hb262",
    legislatureUrl: "https://www.legislature.ohio.gov/legislation/136/hb262",
    textUrl:
      "https://search-prod.lis.state.oh.us/api/v2/general_assembly_136/legislation/hb262/00_IN/pdf/",
  },

  /* ============================================================
     ANTI-LGBTQ+ LAWS, SIGNED / OVERRIDDEN (SCORECARD CONTEXT)
     These bills are no longer movable but remain on the scorecard
     as the record of how each legislator voted. Pipeline is
     complete at step 8 (Governor).
     ============================================================ */
  {
    id: "sb1",
    bill: "SB 1",
    title: "Advance Ohio Higher Education Act (DEI Ban)",
    nickname: "Higher Ed DEI Ban",
    officialTitle: "Enact the Advance Ohio Higher Education Act",
    stance: "anti",
    status: "signed-into-law",
    statusLabel: "Signed Into Law",
    statusColor: "#7f1d1d",
    categories: ["education-dei"],
    categoryLabels: ["Education / DEI"],
    description:
      "Bans diversity, equity, and inclusion offices, programs, and required DEI training at Ohio's public universities and community colleges. Restricts faculty collective bargaining and mandates classroom 'intellectual diversity' reviews. Signed by Gov. DeWine on March 28, 2025.",
    sponsors: "Sen. Jerry Cirino (R-18)",
    lastAction: "Signed into law, March 28, 2025",
    nextDate: "In effect",
    chamber: "senate",
    currentStep: 8,
    pipelineDates: { 8: "Mar 28, 2025" },
    generalAssembly: "136th",
    effectiveDate: "2025-06-26",
    enactedTextUrl: "https://search-prod.lis.state.oh.us/api/v2/general_assembly_136/legislation/sb1/EN/pdf/",
    equalityImpactNote:
      "Eliminates DEI offices, programs, and required training at Ohio's public universities and community colleges. Chills LGBTQ+ student support services, faculty research, and inclusive curriculum.",
    impactedCommunities: ["lgbtq-students", "queer-youth", "transgender-youth", "bipoc-students"],
    url: "/issues/sb1",
    legislatureUrl: "https://www.legislature.ohio.gov/legislation/136/sb1",
    textUrl:
      "https://search-prod.lis.state.oh.us/api/v2/general_assembly_136/legislation/sb1/EN/pdf/",
  },
  {
    id: "sb104",
    bill: "SB 104 (135th GA)",
    title: "Protect All Students Act",
    nickname: "Bathroom Ban",
    officialTitle:
      "Require K-12 schools and higher education institutions to designate separate facilities by biological sex",
    stance: "anti",
    status: "signed-into-law",
    statusLabel: "Signed Into Law",
    statusColor: "#7f1d1d",
    categories: ["anti-trans", "education-dei"],
    categoryLabels: ["Anti-Trans", "Education / DEI"],
    description:
      "Requires K-12 schools, colleges, and universities to designate multi-occupancy restrooms, locker rooms, and overnight accommodations by 'biological sex', barring transgender students from facilities matching their gender identity. Signed by Gov. DeWine on November 27, 2024.",
    sponsors: "Sen. Jerry Cirino (R-18) et al.",
    lastAction: "Signed into law, November 27, 2024",
    nextDate: "In effect",
    chamber: "senate",
    currentStep: 8,
    pipelineDates: { 8: "Nov 27, 2024" },
    generalAssembly: "135th",
    effectiveDate: "2025-02-25",
    enactedTextUrl: "https://search-prod.lis.state.oh.us/api/v2/general_assembly_135/legislation/sb104/EN/pdf/",
    equalityImpactNote:
      "Forces K-12 and higher-ed facilities to be designated by 'biological sex', locking transgender students out of restrooms, locker rooms, and overnight accommodations aligned with their identity.",
    impactedCommunities: ["transgender-youth", "nonbinary-youth", "lgbtq-students"],
    url: "/issues/sb104",
    legislatureUrl: "https://www.legislature.ohio.gov/legislation/135/sb104",
    textUrl:
      "https://search-prod.lis.state.oh.us/api/v2/general_assembly_135/legislation/sb104/EN/pdf/",
  },
  {
    id: "hb8",
    bill: "HB 8 (135th GA)",
    title: "Parents' Bill of Rights",
    nickname: "Forced Outing",
    officialTitle: "Enact the Parents' Bill of Rights",
    stance: "anti",
    status: "signed-into-law",
    statusLabel: "Signed Into Law",
    statusColor: "#7f1d1d",
    categories: ["education-dei", "youth-family"],
    categoryLabels: ["Education / DEI", "Youth / Family"],
    description:
      "Requires schools to notify parents of any change in a student's mental, emotional, or physical health, including requests to use a different name or pronouns, effectively mandating outing of LGBTQ+ students. Restricts instruction on 'sexuality content' in K-3. Signed by Gov. DeWine on December 18, 2024.",
    sponsors: "Rep. D.J. Swearingen (R-89), Rep. Sara Carruthers",
    lastAction: "Signed into law, December 18, 2024",
    nextDate: "In effect",
    chamber: "house",
    currentStep: 8,
    pipelineDates: { 8: "Dec 18, 2024" },
    generalAssembly: "135th",
    effectiveDate: "2025-04-09",
    enactedTextUrl: "https://search-prod.lis.state.oh.us/api/v2/general_assembly_135/legislation/hb8/EN/pdf/",
    equalityImpactNote:
      "Requires school staff to notify parents of any change in a student's mental, emotional, or physical health, including chosen name or pronouns. Functions as a statewide forced-outing mandate for LGBTQ+ youth.",
    impactedCommunities: ["queer-youth", "transgender-youth", "nonbinary-youth", "lgbtq-students"],
    url: "/issues/hb8",
    legislatureUrl: "https://www.legislature.ohio.gov/legislation/135/hb8",
    textUrl:
      "https://search-prod.lis.state.oh.us/api/v2/general_assembly_135/legislation/hb8/EN/pdf/",
  },
  {
    id: "hb68",
    bill: "HB 68 (135th GA)",
    title: "Saving Ohio Adolescents from Experimentation (SAFE) Act",
    nickname: "Gender-Affirming Care Ban + Sports Ban",
    officialTitle:
      "Enact the Saving Ohio Adolescents from Experimentation (SAFE) Act and the Save Women's Sports Act",
    stance: "anti",
    status: "signed-into-law",
    statusLabel: "Law (Veto Overridden)",
    statusColor: "#7f1d1d",
    categories: ["healthcare", "youth-family", "anti-trans"],
    categoryLabels: ["Healthcare", "Youth / Family", "Anti-Trans"],
    description:
      "Bans gender-affirming medical care for transgender minors and bars transgender girls and women from girls' and women's sports teams in K-12 and college. Governor DeWine vetoed the bill on December 29, 2023. The House overrode the veto January 10, 2024, and the Senate followed on January 24, 2024.",
    sponsors: "Rep. Gary Click (R-88)",
    lastAction: "Senate veto override, January 24, 2024",
    nextDate: "In effect",
    chamber: "house",
    currentStep: 8,
    pipelineDates: { 8: "Jan 24, 2024" },
    generalAssembly: "135th",
    effectiveDate: "2024-04-24",
    enactedTextUrl: "https://search-prod.lis.state.oh.us/api/v2/general_assembly_135/legislation/hb68/EN/pdf/",
    equalityImpactNote:
      "Bans gender-affirming medical care for transgender minors and bars transgender girls and women from girls' and women's sports in K-12 and college. Veto overridden. Directly strips medical and athletic access from trans Ohioans.",
    impactedCommunities: ["transgender-youth", "nonbinary-youth", "transgender-adults", "lgbtq-students"],
    url: "/issues/hb68",
    legislatureUrl: "https://www.legislature.ohio.gov/legislation/135/hb68",
    textUrl:
      "https://search-prod.lis.state.oh.us/api/v2/general_assembly_135/legislation/hb68/EN/pdf/",
  },

  /* ============================================================
     PRO-LGBTQ+ BILLS
     ============================================================ */
  {
    id: "sb70",
    bill: "SB 70",
    title: "Ohio Fairness Act",
    nickname: "Statewide Nondiscrimination Protections",
    officialTitle:
      "Enact the Ohio Fairness Act regarding nondiscrimination protections",
    stance: "pro",
    status: "in-committee",
    statusLabel: "In Committee",
    statusColor: "#22c55e",
    categories: ["civil-rights"],
    categoryLabels: ["Civil Rights"],
    description:
      "Adds sexual orientation and gender identity to Ohio's existing nondiscrimination statutes, covering employment, housing, and public accommodations statewide.",
    sponsors: "Sen. Nickie Antonio (D-23)",
    lastAction: "Referred to Senate Judiciary Committee",
    nextDate: "Awaiting committee hearing",
    chamber: "senate",
    currentStep: 1,
    pipelineDates: { 0: "Feb 11, 2025", 1: "Feb 19, 2025" },
    generalAssembly: "136th",
    effectiveDate: null,
    enactedTextUrl: null,
    equalityImpactNote:
      "The Ohio Fairness Act. Adds sexual orientation and gender identity to Ohio's civil-rights code across employment, housing, and public accommodations. The long-sought statewide floor.",
    impactedCommunities: ["all-lgbtq", "transgender-adults", "gay-lesbian-adults", "bisexual-adults", "nonbinary"],
    url: "/issues/sb70",
    legislatureUrl: "https://www.legislature.ohio.gov/legislation/136/sb70",
    textUrl:
      "https://search-prod.lis.state.oh.us/api/v2/general_assembly_136/legislation/sb70/00_IN/pdf/",
  },
  {
    id: "hb136",
    bill: "HB 136",
    title: "Ohio Fairness Act (House)",
    nickname: "House Nondiscrimination Companion",
    officialTitle:
      "Enact the Ohio Fairness Act regarding nondiscrimination protections",
    stance: "pro",
    status: "in-committee",
    statusLabel: "In Committee",
    statusColor: "#22c55e",
    categories: ["civil-rights"],
    categoryLabels: ["Civil Rights"],
    description:
      "House companion to SB 70. Extends Ohio's civil rights protections to include sexual orientation and gender identity across employment, housing, and public accommodations.",
    sponsors: "Rep. Tristan Rader (D-13), Rep. Crystal Lett (D-11)",
    lastAction: "Referred to House Judiciary Committee, March 5, 2025",
    nextDate: "Awaiting committee hearing",
    chamber: "house",
    currentStep: 1,
    pipelineDates: { 0: "Feb 25, 2025", 1: "Mar 5, 2025" },
    generalAssembly: "136th",
    effectiveDate: null,
    enactedTextUrl: null,
    equalityImpactNote:
      "House companion to SB 70. Ohio Fairness Act in the House, same statewide civil-rights expansion to cover sexual orientation and gender identity.",
    impactedCommunities: ["all-lgbtq", "transgender-adults", "gay-lesbian-adults", "bisexual-adults", "nonbinary"],
    url: "/issues/hb136",
    legislatureUrl: "https://www.legislature.ohio.gov/legislation/136/hb136",
    textUrl:
      "https://search-prod.lis.state.oh.us/api/v2/general_assembly_136/legislation/hb136/00_IN/pdf/",
  },
  {
    id: "sb71",
    bill: "SB 71",
    title: "Conversion Therapy Ban",
    nickname: "Protect LGBTQ+ Youth from Conversion Therapy",
    officialTitle:
      "Prohibit licensed professionals from practicing conversion therapy on minors",
    stance: "pro",
    status: "in-committee",
    statusLabel: "In Committee",
    statusColor: "#22c55e",
    categories: ["healthcare", "youth-family"],
    categoryLabels: ["Healthcare", "Youth / Family"],
    description:
      "Prohibits state-licensed mental health professionals from subjecting minors to conversion therapy, a discredited practice rejected by every major medical association.",
    sponsors: "Sen. Nickie Antonio (D-23)",
    lastAction: "Referred to Senate Health Committee",
    nextDate: "Awaiting committee hearing",
    chamber: "senate",
    currentStep: 1,
    pipelineDates: { 0: "Feb 11, 2025", 1: "Feb 19, 2025" },
    generalAssembly: "136th",
    effectiveDate: null,
    enactedTextUrl: null,
    equalityImpactNote:
      "Bans licensed professionals from subjecting minors to conversion therapy, a practice rejected by every major medical association. Protects LGBTQ+ youth from state-sanctioned harm.",
    impactedCommunities: ["queer-youth", "transgender-youth", "nonbinary-youth"],
    url: "/issues/sb71",
    legislatureUrl: "https://www.legislature.ohio.gov/legislation/136/sb71",
    textUrl:
      "https://search-prod.lis.state.oh.us/api/v2/general_assembly_136/legislation/sb71/00_IN/pdf/",
  },
  {
    id: "hb300",
    bill: "HB 300",
    title: "Conversion Therapy Ban (House)",
    nickname: "House Conversion Therapy Companion",
    officialTitle:
      "Prohibit licensed professionals from practicing conversion therapy on minors",
    stance: "pro",
    status: "introduced",
    statusLabel: "Introduced",
    statusColor: "#22c55e",
    categories: ["healthcare", "youth-family"],
    categoryLabels: ["Healthcare", "Youth / Family"],
    description:
      "House companion to SB 71. Bans conversion therapy on minors by licensed professionals. Supported by the American Medical Association, American Psychological Association, and American Academy of Pediatrics.",
    sponsors: "Rep. Karen Brownlee (D-28), Rep. Crystal Lett (D-11)",
    lastAction: "Referred to House Health Committee, May 28, 2025",
    nextDate: "Awaiting committee hearing",
    chamber: "house",
    currentStep: 1,
    pipelineDates: { 0: "May 21, 2025", 1: "May 28, 2025" },
    generalAssembly: "136th",
    effectiveDate: null,
    enactedTextUrl: null,
    equalityImpactNote:
      "House companion to SB 71. Conversion therapy ban for minors by licensed professionals. AMA, APA, and AAP supported.",
    impactedCommunities: ["queer-youth", "transgender-youth", "nonbinary-youth"],
    url: "/issues/hb300",
    legislatureUrl: "https://www.legislature.ohio.gov/legislation/136/hb300",
    textUrl:
      "https://search-prod.lis.state.oh.us/api/v2/general_assembly_136/legislation/hb300/00_IN/pdf/",
  },
  {
    id: "hjr4",
    bill: "HJR 4",
    title: "Marriage Equality Act",
    nickname: "Repeal Ohio's 2004 Same-Sex Marriage Ban",
    officialTitle:
      "Amend Article XV Section 11 of the Constitution of Ohio regarding marriage",
    stance: "pro",
    status: "in-committee",
    statusLabel: "In Committee",
    statusColor: "#22c55e",
    categories: ["civil-rights"],
    categoryLabels: ["Civil Rights"],
    description:
      "Constitutional amendment to repeal Ohio's dormant 2004 same-sex marriage ban and recognize the right to interracial marriage in the Ohio Constitution. Would let Ohio voters codify marriage equality independent of federal precedent. No committee hearings have been held to date.",
    sponsors: "Rep. Eric Synenberg (D-22), Rep. Anita Somani (D-11)",
    lastAction: "Referred to House Judiciary Committee, June 2025",
    nextDate: "Awaiting committee hearing",
    chamber: "house",
    currentStep: 1,
    pipelineDates: { 0: "Jun 3, 2025", 1: "Jun 2025" },
    generalAssembly: "136th",
    effectiveDate: null,
    enactedTextUrl: null,
    equalityImpactNote:
      "Constitutional amendment repealing Ohio's dormant 2004 same-sex marriage ban and affirming the right to interracial marriage in the Ohio Constitution. Locks in marriage equality independent of federal precedent.",
    impactedCommunities: ["same-sex-couples", "interracial-couples", "lgbtq-families", "all-lgbtq"],
    url: "/issues/hjr4",
    legislatureUrl: "https://www.legislature.ohio.gov/legislation/136/hjr4",
    textUrl:
      "https://search-prod.lis.state.oh.us/api/v2/general_assembly_136/legislation/hjr4/00_IN/pdf/",
  },
  {
    id: "hb327",
    bill: "HB 327",
    title: "PRIDE Act",
    nickname: "Parental Rights for Affirming Families",
    officialTitle: "Enact the Parental Rights in Diverse Environments Act",
    stance: "pro",
    status: "in-committee",
    statusLabel: "In Committee",
    statusColor: "#22c55e",
    categories: ["youth-family", "civil-rights"],
    categoryLabels: ["Youth / Family", "Civil Rights"],
    description:
      "Protects parents who affirm and support their LGBTQ+ children from state interference. Ensures affirming parenting decisions cannot be used as grounds for custody challenges or abuse allegations.",
    sponsors: "Rep. Karen Brownlee (D-28), Rep. Darnell Brewer (D-23)",
    lastAction:
      "Referred to House Children and Human Services Committee, June 11, 2025",
    nextDate: "Awaiting committee hearing",
    chamber: "house",
    currentStep: 1,
    pipelineDates: { 0: "Jun 3, 2025", 1: "Jun 11, 2025" },
    generalAssembly: "136th",
    effectiveDate: null,
    enactedTextUrl: null,
    equalityImpactNote:
      "The PRIDE Act. Shields affirming parents of LGBTQ+ children from state interference, custody challenges, and abuse allegations rooted in their child's identity.",
    impactedCommunities: ["lgbtq-families", "transgender-youth", "queer-youth", "nonbinary-youth"],
    url: "/issues/hb327",
    legislatureUrl: "https://www.legislature.ohio.gov/legislation/136/hb327",
    textUrl:
      "https://search-prod.lis.state.oh.us/api/v2/general_assembly_136/legislation/hb327/00_IN/pdf/",
  },
  {
    id: "sb211",
    bill: "SB 211",
    title: "Love Makes a Family Week",
    nickname: "Celebrate Diverse Ohio Families",
    officialTitle: "Designate Love Makes a Family Week in Ohio",
    stance: "pro",
    status: "introduced",
    statusLabel: "Introduced",
    statusColor: "#22c55e",
    categories: ["youth-family"],
    categoryLabels: ["Youth / Family"],
    description:
      "Designates a week celebrating the diversity of Ohio families, including LGBTQ+ families, adoptive families, and nontraditional households. A direct counterpoint to HB 262's 'Natural Family Month.'",
    sponsors: "Sen. Nickie Antonio (D-23)",
    lastAction: "Introduced, October 14, 2025",
    nextDate: "Awaiting committee assignment",
    chamber: "senate",
    currentStep: 0,
    pipelineDates: { 0: "Oct 14, 2025" },
    generalAssembly: "136th",
    effectiveDate: null,
    enactedTextUrl: null,
    equalityImpactNote:
      "Designates Love Makes a Family Week in Ohio, affirmatively recognizing LGBTQ+, adoptive, and nontraditional families. Direct counter to HB 262's 'Natural Family Month'.",
    impactedCommunities: ["lgbtq-families", "same-sex-couples", "adoptive-families"],
    url: "/issues/sb211",
    legislatureUrl: "https://www.legislature.ohio.gov/legislation/136/sb211",
    textUrl:
      "https://search-prod.lis.state.oh.us/api/v2/general_assembly_136/legislation/sb211/00_IN/pdf/",
  },

  /* ============================================================
     MIXED BILLS
     ============================================================ */
  {
    id: "hb306",
    bill: "HB 306",
    title: "Hate Crimes Act",
    nickname: "Hate Crimes, Excludes Trans Protections",
    officialTitle: "Enact the Ohio Hate Crimes Act",
    stance: "mixed",
    status: "in-committee",
    statusLabel: "In Committee",
    statusColor: "#eab308",
    categories: ["civil-rights"],
    categoryLabels: ["Civil Rights"],
    description:
      "Creates enhanced penalties for hate crimes based on race, religion, national origin, disability, and sexual orientation, but notably excludes gender identity, leaving transgender Ohioans without protection.",
    sponsors: "Rep. Brett Hillyer (R-37), Rep. Bride Rose Sweeney (D-16)",
    lastAction:
      "1st hearing in House Criminal Justice Committee, February 25, 2026",
    nextDate: "Additional hearings expected",
    chamber: "house",
    currentStep: 2,
    pipelineDates: { 0: "May 27, 2025", 1: "Jun 4, 2025", 2: "Feb 25, 2026" },
    generalAssembly: "136th",
    effectiveDate: null,
    enactedTextUrl: null,
    equalityImpactNote:
      "Hate Crimes Act that enumerates sexual orientation but omits gender identity. Partial win, since trans Ohioans remain outside the enhanced-penalty regime and any unamended passage sets a harmful precedent.",
    impactedCommunities: ["gay-lesbian-adults", "bisexual-adults", "transgender-adults", "all-lgbtq"],
    url: "/issues/hb306",
    legislatureUrl: "https://www.legislature.ohio.gov/legislation/136/hb306",
    textUrl:
      "https://search-prod.lis.state.oh.us/api/v2/general_assembly_136/legislation/hb306/00_IN/pdf/",
  },
];

// Helper to find a bill by ID
function getBillById(id) {
  return BILLS.find((b) => b.id === id);
}

/* Last synced to Ohio Pride PAC Supabase bill-table: 2026-04-22. Source of truth is public.bills. */
