/**
 * tests/vote-pages.test.mjs
 * -------------------------
 * The acceptance checks for the Drag Out The Vote pages, so they run on every
 * `npm test` instead of once at review:
 *
 *   - both pages match public/vote/config.js (nothing date-shaped was typed
 *     into the HTML by hand and left to drift)
 *   - the copy rules hold across public/vote and public/dragoutthevote:
 *     no em or en dashes, "absentee ballot" never "mail ballot" or "mail-in",
 *     no "openly", no "first statewide", no "Paid for by" (the site footer
 *     carries the disclaimer; the pages themselves must not)
 *   - the config is internally consistent
 */

import assert from 'node:assert/strict';
import { readdirSync, readFileSync, statSync, existsSync } from 'node:fs';
import { dirname, join, extname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { test } from 'node:test';
import CONFIG from '../public/vote/config.js';
import { PAGE_FILES, applyTo, derive, captionText } from '../scripts/build-vote.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const DIRS = ['public/vote', 'public/dragoutthevote'];
const TEXT = new Set(['.html', '.js', '.css', '.md', '.txt', '.json', '.svg']);

function textFiles(dir, found = []) {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) textFiles(full, found);
    else if (TEXT.has(extname(entry))) found.push(full);
  }
  return found;
}

const files = DIRS.flatMap((dir) => textFiles(join(ROOT, dir)));

test('both pages match config.js', () => {
  for (const rel of PAGE_FILES) {
    const source = readFileSync(join(ROOT, rel), 'utf8');
    assert.equal(applyTo(source), source, `${rel} is stale. Run: npm run vote:build`);
  }
});

test('no em or en dashes anywhere under the two page directories', () => {
  /* The one exemption is the opening marker of the generated SEO block,
   * `<!-- seo:start — generated by ... -->`, which scripts/build-seo.mjs
   * writes into every page on the site and which is an HTML comment, not
   * copy. Everything else, comments included, is held to the rule. */
  const SEO_MARKER = /<!-- seo:start [^>]*-->/g;
  for (const file of files) {
    const text = readFileSync(file, 'utf8').replace(SEO_MARKER, '');
    const hit = text.match(/[–—]/);
    assert.equal(hit, null, `${file} contains a dash at index ${hit?.index}`);
  }
});

test('forbidden phrases never appear', () => {
  const banned = [/mail ballot/i, /mail-in/i, /\bopenly\b/i, /first statewide/i, /paid for by/i];
  for (const file of files) {
    const text = readFileSync(file, 'utf8');
    for (const re of banned) {
      assert.equal(re.test(text), false, `${file} matches ${re}`);
    }
  }
});

test('config is internally consistent', () => {
  const ctx = derive(CONFIG);
  assert.ok(CONFIG.POLLS_OPEN_AT.startsWith(CONFIG.ELECTION_DAY), 'POLLS_OPEN_AT is not on Election Day');
  assert.ok(CONFIG.POLLS_CLOSE_AT.startsWith(CONFIG.ELECTION_DAY), 'POLLS_CLOSE_AT is not on Election Day');
  assert.ok(new Date(CONFIG.POLLS_OPEN_AT) < new Date(CONFIG.POLLS_CLOSE_AT));
  assert.ok(CONFIG.EARLY_VOTING_OPENS < CONFIG.EARLY_VOTING_CLOSES);
  assert.ok(CONFIG.EARLY_VOTING_CLOSES < CONFIG.ELECTION_DAY);
  assert.equal(CONFIG.WEEKS.length, 5);
  assert.equal(ctx.ELECTION_DAY_WEEKDAY, 'Tuesday', 'Ohio general elections are on a Tuesday');
  for (const week of CONFIG.WEEKS) {
    assert.equal(week.hashtags[0], CONFIG.HASHTAG, `week ${week.number} does not lead with the campaign tag`);
    assert.equal(week.hashtags.at(-1), '#OhioPride', `week ${week.number} does not end with #OhioPride`);
    for (const path of [week.feed, week.story]) {
      assert.ok(existsSync(join(ROOT, 'public', path)), `week ${week.number} graphic missing: ${path}`);
    }
    const text = captionText(week, ctx);
    const lines = text.split('\n');
    assert.equal(lines.at(-2), CONFIG.VOTE_URL, 'the link is not on its own line before the hashtags');
  }
});
