#!/usr/bin/env node
/**
 * scripts/build-seo.mjs
 * ---------------------
 * Writes the SEO <head> block into every static page under public/.
 *
 *   npm run seo:build     rewrite the pages
 *   npm run seo:build -- --check   fail if any page is out of date (CI)
 *
 * The block is delimited by `<!-- seo:start -->` / `<!-- seo:end -->` and is
 * rebuilt from lib/seo.mjs on every run, so it is safe to run repeatedly and
 * pointless to edit by hand. Everything else in the <head> — stylesheets, font
 * preconnects, page-scoped <style> — is left exactly where it was.
 *
 * The generator owns a fixed set of tags and removes only those: <title>, the
 * description/robots/theme-color metas, every og: and twitter: meta, the
 * canonical link, the icon links, and JSON-LD scripts. A page can still add
 * its own <meta> for anything outside that set.
 *
 * Why generate rather than hand edit: before this existed, 22 of the 58 pages
 * shipped `<title>Loading... | Ohio Pride</title>` because the real title was
 * set from JavaScript, 45 had no og:image at all, and the canonical host was
 * www on some pages and the apex on others. Those are the kinds of mistakes
 * that come back the moment a page is added by hand.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { pathToFileURL } from 'node:url';
import {
  DEFAULT_OG_IMAGE,
  DEFAULT_OG_IMAGE_ALT,
  SITE_NAME,
  THEME_COLOR,
  absolute,
  allStaticPages,
  fileFor,
  jsonLdFor,
} from '../lib/seo.mjs';

const CHECK_ONLY = process.argv.includes('--check');

const START = '<!-- seo:start — generated by `npm run seo:build` from lib/seo.mjs. Do not edit. -->';
const END = '<!-- seo:end -->';

const esc = (value) =>
  String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');

/* -------------------------------------------------------------------------
 * The generated block.
 * ---------------------------------------------------------------------- */
export function headBlock(page, indent = '    ') {
  const image = absolute(page.image || DEFAULT_OG_IMAGE);
  const imageAlt = page.imageAlt || DEFAULT_OG_IMAGE_ALT;
  const lines = [];
  const meta = (attr, name, content) =>
    lines.push(`<meta ${attr}="${name}" content="${esc(content)}" />`);

  lines.push(`<title>${esc(page.title)}</title>`);
  meta('name', 'description', page.description);

  if (page.noindex) {
    // nofollow is deliberately not set: these pages link back into the public
    // site, and there is no reason to strand those links.
    meta('name', 'robots', 'noindex, follow');
  } else {
    lines.push(`<link rel="canonical" href="${absolute(page.url)}" />`);
    // max-image-preview:large is what lets Google use the full-width card in
    // Discover and image-rich results instead of a thumbnail.
    meta('name', 'robots', 'index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1');
  }

  meta('name', 'theme-color', THEME_COLOR);

  lines.push('');
  meta('property', 'og:type', page.type || 'website');
  // One spelling of the brand in every card. Pages used to alternate between
  // "Ohio Pride" and "Ohio Pride PAC" depending on who wrote the page.
  meta('property', 'og:site_name', SITE_NAME);
  meta('property', 'og:locale', 'en_US');
  meta('property', 'og:title', page.ogTitle || page.title);
  meta('property', 'og:description', page.ogDescription || page.description);
  meta('property', 'og:url', absolute(page.url));
  meta('property', 'og:image', image);
  meta('property', 'og:image:width', '1200');
  meta('property', 'og:image:height', '630');
  meta('property', 'og:image:alt', imageAlt);

  lines.push('');
  meta('name', 'twitter:card', 'summary_large_image');
  meta('name', 'twitter:title', page.ogTitle || page.title);
  meta('name', 'twitter:description', page.ogDescription || page.description);
  meta('name', 'twitter:image', image);
  meta('name', 'twitter:image:alt', imageAlt);

  lines.push('');
  lines.push('<link rel="icon" href="/favicon.ico" sizes="any" />');
  lines.push('<link rel="icon" type="image/svg+xml" href="/assets/favicon/favicon.svg" />');
  lines.push('<link rel="icon" type="image/png" sizes="32x32" href="/assets/favicon/favicon-32.png" />');
  lines.push('<link rel="icon" type="image/png" sizes="16x16" href="/assets/favicon/favicon-16.png" />');
  lines.push('<link rel="apple-touch-icon" sizes="180x180" href="/assets/favicon/apple-touch-icon.png" />');

  for (const graph of jsonLdFor(page)) {
    lines.push('');
    lines.push('<script type="application/ld+json">');
    lines.push(...JSON.stringify(graph, null, 2).split('\n'));
    lines.push('</script>');
  }

  const body = lines
    .map((line) => (line === '' ? '' : indent + line))
    .join('\n');
  return `${indent}${START}\n${body}\n${indent}${END}`;
}

/* -------------------------------------------------------------------------
 * Surgery on an existing document.
 *
 * Only the <head> is touched, and inside it only the tags the generator owns.
 * The matchers tolerate tags broken across lines, which several pages do.
 * ---------------------------------------------------------------------- */

// A tag's attribute soup, quote aware so a ">" inside an attribute value does
// not end the match early.
const ATTRS = '(?:[^>"\']|"[^"]*"|\'[^\']*\')*';
const wholeLine = (pattern) => new RegExp(`^[ \\t]*${pattern}[ \\t]*\\r?\\n?`, 'gm');

const MANAGED_META = /(?:name|property)\s*=\s*["'](?:description|robots|googlebot|theme-color|og:[\w:]+|twitter:[\w:]+)["']/i;
const MANAGED_LINK = /rel\s*=\s*["'](?:canonical|icon|shortcut icon|apple-touch-icon|mask-icon|manifest)["']/i;

/* Section labels the old hand-written heads used. Once the tags underneath
 * them move into the generated block the comment is left pointing at nothing,
 * so it goes too. INJECT_OG_TAGS_HERE was a placeholder from a build step that
 * no longer exists. */
const STALE_COMMENTS = /^[ \t]*<!--\s*(?:Open Graph|Twitter(?: Card)?|Favicons?|SEO(?:[^>]*)?|JSON-LD[^>]*|INJECT_OG_TAGS_HERE)\s*-->[ \t]*\r?\n?/gim;

function stripManaged(head) {
  return head
    .replace(wholeLine(`<!-- seo:start[\\s\\S]*?seo:end -->`), '')
    .replace(STALE_COMMENTS, '')
    .replace(wholeLine(`<title>[\\s\\S]*?<\\/title>`), '')
    .replace(wholeLine(`<script\\s+type=["']application\\/ld\\+json["'][\\s\\S]*?<\\/script>`), '')
    .replace(wholeLine(`<meta\\b${ATTRS}>`), (tag) => (MANAGED_META.test(tag) ? '' : tag))
    .replace(wholeLine(`<link\\b${ATTRS}>`), (tag) => (MANAGED_LINK.test(tag) ? '' : tag))
    // Collapse the holes the removals left behind.
    .replace(/\n{3,}/g, '\n\n');
}

/* -------------------------------------------------------------------------
 * Bill pages: fill the hero from the same data the page's JavaScript uses.
 *
 * public/js/bill-detail.js writes the bill number, title, nickname, official
 * title, status and meta cards into empty elements on DOMContentLoaded. That
 * left the served document with an empty <h1> and no sponsor, status, or date
 * text anywhere in the HTML — everything a crawler weighs most, available only
 * after it chooses to run the page's scripts.
 *
 * Writing the same values in at build time costs nothing at runtime: the
 * script sets textContent on the same nodes to the same strings, so the page
 * behaves identically and the document is no longer empty without JavaScript.
 * The three hand-written bill pages (hb96, hb112, hb838) have no such
 * placeholders and are skipped by the simple fact that nothing matches.
 * ---------------------------------------------------------------------- */
function fillPlaceholders(source, page) {
  const bill = page.bill;
  if (!bill) return source;

  const text = {
    billNumber: bill.bill,
    billTitle: bill.title,
    billNickname: bill.nickname || '',
    billOfficialTitle: bill.officialTitle || bill.title,
    statusBadge: bill.statusLabel,
    billSponsors: bill.sponsors || '',
    billLastAction: bill.lastAction || '',
    billNextDate: bill.nextDate || '',
    billHouseVote: bill.houseVote || '',
  };

  let out = source;
  for (const [id, value] of Object.entries(text)) {
    const el = new RegExp(`(<(\\w+)((?:[^>"']|"[^"]*"|'[^']*')*\\bid="${id}"(?:[^>"']|"[^"]*"|'[^']*')*)>)([\\s\\S]*?)(</\\2>)`);
    out = out.replace(el, (whole, open, tag, attrs, _inner, close) => `${open}${esc(value)}${close}`);
  }

  // The two outbound links are also assigned by the script. A real href in the
  // document is a real link out to the Ohio Legislature; href="#" is not.
  for (const [id, href] of [
    ['legislatureLink', bill.legislatureUrl],
    ['textLink', bill.textUrl],
  ]) {
    if (!href) continue;
    const anchor = new RegExp(`(<a\\b(?:[^>"']|"[^"]*"|'[^']*')*\\bid="${id}"(?:[^>"']|"[^"]*"|'[^']*')*>)`);
    out = out.replace(anchor, (tag) => tag.replace(/href="[^"]*"/, `href="${esc(href)}"`));
  }
  return out;
}

/** Rewrite one document. Returns the new source, or null when unchanged. */
export function applyTo(source, page) {
  const headStart = source.indexOf('<head');
  const headEnd = source.indexOf('</head>');
  if (headStart === -1 || headEnd === -1) throw new Error('no <head> in document');

  const before = source.slice(0, headStart);
  const after = source.slice(headEnd);
  let head = stripManaged(source.slice(headStart, headEnd));

  // Anchor the block below the viewport meta: charset and viewport must stay
  // first, and everything else in the head is presentation.
  const viewport = head.match(new RegExp(`^([ \\t]*)<meta\\b${ATTRS}name=["']viewport["']${ATTRS}>[ \\t]*\\r?\\n`, 'm'));
  if (!viewport) throw new Error('no viewport meta to anchor the block to');

  const indent = viewport[1] || '    ';
  const at = viewport.index + viewport[0].length;
  head = `${head.slice(0, at)}\n${headBlock(page, indent)}\n${head.slice(at)}`;

  const next = fillPlaceholders(before + head + after, page);
  return next === source ? null : next;
}

/* ------------------------------------------------------------------------ */

function main() {
const pages = allStaticPages();
const changed = [];
const missing = [];

for (const page of pages) {
  const file = fileFor(page.url);
  if (!file) {
    missing.push(page.url);
    continue;
  }
  const source = readFileSync(file, 'utf8');
  let next;
  try {
    next = applyTo(source, page);
  } catch (err) {
    console.error(`✗ ${page.url}: ${err.message}`);
    process.exitCode = 1;
    continue;
  }
  if (!next) continue;
  changed.push(page.url);
  if (!CHECK_ONLY) writeFileSync(file, next);
}

if (missing.length) {
  console.error(`✗ ${missing.length} page(s) in lib/seo.mjs have no file under public/:`);
  for (const url of missing) console.error(`    ${url}`);
  process.exitCode = 1;
}

if (CHECK_ONLY) {
  if (changed.length) {
    console.error(`✗ ${changed.length} page(s) have a stale SEO block. Run: npm run seo:build`);
    for (const url of changed) console.error(`    ${url}`);
    process.exitCode = 1;
  } else if (!missing.length) {
    console.log(`✓ SEO blocks up to date across ${pages.length} pages`);
  }
} else {
  console.log(
    changed.length
      ? `✓ wrote ${changed.length} of ${pages.length} pages:\n    ${changed.join('\n    ')}`
      : `✓ all ${pages.length} pages already up to date`,
  );
}
}

/* Importable as a module — scripts/check-seo.mjs reuses applyTo() to tell
 * whether a page is stale, and importing it must not rewrite the repo. */
if (process.argv[1] && pathToFileURL(process.argv[1]).href === import.meta.url) main();
